### ISSUE TITLE
DjangoPermissionRequiredMixin: UnitTests fail even when only the order of permissions changes 

### ISSUE THREAD

**Issue by esskaey** [ambient-innovation/ai-django-core#10]
Hi,

I have recently started using your package after getting introduced to it from Ronny and it has been really helpful in bringing order and structure to my project. So first thank you very much for publishing this package and for maintaining it. 

I am currently finding that the unittests for views with DjangoPermissionRequiredMixin fails when the order of permissions changes, i.e.,  the permission items are the same but with different order. Is assertCountEqual instead of assertEqual a possible option  here ? , to compare the permissions defined between test and the actual view class ? 

Thanks!

BR

**Comment by GitRon** [comment]
Hi! Thx for the hint, I'll have a look as soon as I find a minute for this project 👍

**Comment by GitRon** [comment]
Hi @esskaey - I fixed the issue and a new version is pushed to PyPI.
