### ISSUE TITLE
Documentation of `EmailTestServiceQuerySet._get_txt_content` is wrong

### ISSUE THREAD

**Issue by Bergiu** [ambient-innovation/ai-django-core#2]
`Ensure we just have found one element and then return HTML part of the email`

should be:

`Ensure we just have found one element and then return body of the email` or `Return body of the email`

Also where is the check that there is only one element?

**Comment by GitRon** [comment]
True, thanks for the hint! Will fix it ASAP.

**Comment by GitRon** [comment]
Hm, after a second look I think it is still correct because this method returns the html body. The other one returns the txt part. 🤔

**Comment by GitRon** [comment]
I updated the docstring. Fixed 🎉
