### ISSUE TITLE
CommonInfo and CreatedAtInfo improvements

### ISSUE THREAD

**Issue by jose-zitus** [ambient-innovation/ai-django-core#5]
### Description

As of version 5.6.0 of ai-django-core, I believe there is a little room for improvement on these models:

- It uses default=now on created_at and lastmodified_at fields, instead of the good old auto_now=True and auto_now_add=True, which is cleaner and does not make these fields visible/editable on modelForms by default, which is ideal for audit purposes.
- The created_by and lastmodified_by fields should have the editable flag set to False so they are fully automatic and not visible on forms by default.

The current settings are not wrong, but I believe the ones I'm proposing suit more the typical use case for Django Models.

### How I believe the fields should look like

```
created_at = models.DateTimeField(_("Created at"), auto_now_add=True, db_index=True)
created_by = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("Created by"), blank=True, null=True,
                                   related_name="%(app_label)s_%(class)s_created", on_delete=models.SET_NULL, editable=False)
lastmodified_at = models.DateTimeField(_("Last modified at"), auto_now=True, db_index=True)
lastmodified_by = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("Last modified by"), blank=True,
                                        null=True, related_name="%(app_label)s_%(class)s_lastmodified",
                                        on_delete=models.SET_NULL, editable=False)
```

**Comment by GitRon** [comment]
Hi @jose-zitus - thanks for the hint! Actually, this is a feature! In some cases for this universally usable library it is required to manually set the timestamps. That's why we implemented it this way. If you use the middleware these values should be set correctly anyway, right?

Best regards!
Ronny
